# Atividade prática - Introdução
A atividade sugerida faz uso dos dados de uma base modifica [IGM - Índice Governança Municipal](https://www.kaggle.com/datasets/joaoavf/igm-indice-governancao-municipal). Os dados foram alterados e simplificados pelo professor da disciplina

# Imports

In [65]:
import pandas as pd
pd.set_option("display.max_columns", 500)

# Leitura e apresentação dos dados

In [66]:
caminho_csv = '../../datasets/igm_modificado.csv'
dataframe = pd.read_csv(caminho_csv, sep=',', encoding='utf-8', thousands=',')
dataframe.head()

,regiao,estado,municipio,codigo_mun,capital,porte,populacao,area,densidade_dem,pib,pib_pc,participacao_transf_receita,servidores,comissionados,comissionados_por_servidor,perc_pop_econ_ativa,taxa_empreendedorismo,anos_estudo_empreendedor,jornada_trabalho,gasto_pc_saude,hab_p_medico,exp_vida,gasto_pc_educacao,exp_anos_estudo,nota_ciencias,nota_humanas,nota_linguagem,nota_mat,nota_redacao,idhm,ranking_igm,indice_governanca
0,SUDESTE,SP,ILHABELA,3520400,0,Pequeno porte 2,"32,782",347.52,81.1,3.256712e+06,105112.86,77.0,1495.0,74.0,5%,1.18,0.22,8.436129,42.726231,1529.48,394.987500,75.56,1734.52,10.63,482.054348,541.226087,530.651111,507.952778,499.361111,0.747,1º,0.767
1,SUDESTE,SP,SANTANA DE PARNAIBA,3547304,0,Grande porte,"129,261",179.95,604.7,7.373603e+06,60939.87,51.0,6157.0,587.0,10%,1.04,0.25,10.869492,42.542935,1017.67,400.728155,75.92,1704.93,10.01,483.997625,542.760422,535.765129,499.911091,547.506655,0.885,2º,0.759
2,SUL,SC,BOMBINHAS,4202453,0,Pequeno porte 1,"18,052",35.92,398.0,3.773573e+05,23135.14,32.0,583.0,48.0,8%,1.09,0.32,8.836678,40.314335,830.70,1126.466667,76.86,1370.96,10.44,472.105607,541.949533,523.251923,474.506731,515.000000,0.807,3º,0.758
3,SUDESTE,SP,SAO BERNARDO DO CAMPO,3548708,0,Grande porte,"822,242",409.53,1869.4,4.766853e+07,59149.80,49.0,10673.0,611.0,6%,1.09,0.18,9.659424,42.620522,1113.74,2459.057576,76.65,770.79,10.22,489.241514,552.616190,546.173721,514.204358,557.668055,0.864,4º,0.756
4,CENTRO-OESTE,DF,BRASILIA,5300108,1,Grande porte,"2,977,216",5780.00,444.7,1.753628e+08,62859.43,35.0,119072.0,6288.0,5%,1.10,0.18,9.187700,39.546426,1982.45,572.880498,77.35,2077.49,9.87,493.514758,551.982498,538.366612,509.206006,567.991533,0.909,5º,0.736

Quantos linhas e colunas?

In [67]:
print(f'Linhas: {dataframe.shape[0]}\nColunas: {dataframe.shape[1]}')

Linhas: 5570
Colunas: 32

In [68]:
dataframe.describe()

,codigo_mun,capital,area,densidade_dem,pib,pib_pc,participacao_transf_receita,servidores,comissionados,perc_pop_econ_ativa,taxa_empreendedorismo,anos_estudo_empreendedor,jornada_trabalho,gasto_pc_saude,hab_p_medico,exp_vida,gasto_pc_educacao,exp_anos_estudo,nota_ciencias,nota_humanas,nota_linguagem,nota_mat,nota_redacao,idhm,indice_governanca
count,5.570000e+03,5570.000000,5570.000000,5566.000000,5.570000e+03,5570.000000,4893.000000,5233.000000,5570.000000,5565.000000,5570.000000,5570.000000,5570.000000,4881.000000,4951.000000,5565.000000,4880.000000,5565.000000,5558.000000,5558.000000,5557.000000,5557.000000,5557.000000,4986.000000,3303.000000
mean,3.253591e+06,0.004847,1526.532426,108.189026,9.544801e+05,17374.483108,82.316575,771.324861,96.371275,0.936503,0.250939,6.124378,41.414005,604.508021,1801.408820,73.088996,769.775533,9.463639,460.124417,509.526944,499.286922,465.007784,501.840952,0.518626,0.501959
std,9.849103e+05,0.069461,5607.553417,572.067148,9.502661e+06,20133.341193,11.272136,3209.755931,234.994469,0.178640,0.098014,1.462946,5.193799,282.184671,2203.553117,2.680715,277.841845,1.098269,19.275298,23.816077,22.056169,28.496300,44.904955,0.171847,0.083704
min,1.100015e+06,0.000000,3.570000,0.100000,9.678440e+03,3241.290000,0.000000,1.000000,0.000000,0.290000,0.000000,0.000000,0.000000,3.800000,85.746835,65.300000,56.600000,4.340000,385.000000,373.800000,404.000000,369.275000,320.000000,0.000000,0.258000
25%,2.512126e+06,0.000000,204.245000,11.600000,5.922529e+04,7077.357500,77.000000,190.000000,24.000000,0.810000,0.190000,5.039926,38.151867,416.930000,967.636243,71.150000,585.892500,8.750000,446.324306,492.975737,483.454286,443.078082,473.125000,0.375000,0.438000
50%,3.146280e+06,0.000000,417.980000,24.400000,1.301531e+05,12621.810000,85.000000,329.000000,45.000000,0.940000,0.230000,6.049990,41.718024,537.480000,1457.062500,73.470000,731.825000,9.470000,457.549922,508.987016,499.105769,461.261538,502.406015,0.535000,0.504000
75%,4.119190e+06,0.000000,1026.165000,51.700000,3.426808e+05,21262.387500,91.000000,663.000000,92.000000,1.050000,0.290000,7.175247,44.682323,717.760000,2119.679487,75.160000,898.625000,10.210000,471.752760,526.405985,515.125917,483.773196,532.173913,0.659000,0.566000
max,5.300108e+06,1.000000,159533.260000,13024.600000,5.707062e+08,715193.700000,100.000000,134273.000000,7240.000000,1.640000,0.770000,11.553164,68.528406,3066.740000,78464.666667,78.640000,3695.930000,12.830000,550.566667,595.160000,571.659503,603.415000,668.000000,1.000000,0.767000

# Dados do Espírito Santo

In [69]:
dataframe_es = dataframe[dataframe['estado'] == 'ES']
dataframe_es.head()

,regiao,estado,municipio,codigo_mun,capital,porte,populacao,area,densidade_dem,pib,pib_pc,participacao_transf_receita,servidores,comissionados,comissionados_por_servidor,perc_pop_econ_ativa,taxa_empreendedorismo,anos_estudo_empreendedor,jornada_trabalho,gasto_pc_saude,hab_p_medico,exp_vida,gasto_pc_educacao,exp_anos_estudo,nota_ciencias,nota_humanas,nota_linguagem,nota_mat,nota_redacao,idhm,ranking_igm,indice_governanca
14,SUDESTE,ES,VITORIA,3205309,1,Grande porte,"359,555",96.54,3338.3,22289815.47,64001.91,49.0,10031.0,713.0,7%,1.09,0.23,11.008352,40.788846,671.86,768.786026,76.28,957.78,10.04,524.303488,573.910971,548.750702,550.990412,596.203790,0.959,15º,0.702
79,SUDESTE,ES,ARACRUZ,3200607,0,Médio porte,"96,746",1423.87,57.5,5214973.56,56955.65,58.0,2439.0,286.0,12%,1.05,0.18,8.047370,42.441800,656.78,NaN,75.26,957.77,10.26,494.250831,542.990736,520.793533,507.556527,542.706587,0.737,80º,0.656
93,SUDESTE,ES,PIUMA,3204203,0,Pequeno porte 2,"21,030",74.82,242.2,446855.58,22251.55,78.0,682.0,226.0,33%,1.01,0.33,7.609606,44.256493,733.27,1568.846154,76.11,1104.82,9.04,488.720642,543.978899,524.978704,491.847685,552.592593,0.678,94º,0.652
174,SUDESTE,ES,LINHARES,3203205,0,Grande porte,"166,491",3504.14,40.3,5178698.58,32815.20,70.0,5698.0,653.0,11%,1.07,0.20,7.945812,40.722908,806.25,NaN,75.05,837.31,8.97,482.997684,530.750496,513.277793,492.214132,519.544415,0.671,175º,0.635
227,SUDESTE,ES,MARATAIZES,3203320,0,Pequeno porte 2,"38,301",133.08,256.6,4501549.26,121204.88,81.0,1730.0,205.0,12%,0.87,0.41,5.955546,41.564949,918.00,781.979167,75.80,1651.20,8.61,475.041975,529.328086,504.486478,486.729245,536.113208,0.604,228º,0.623

In [70]:
dataframe_es.shape

(78, 32)

Podemos observar na saida acima que, de fato, temos 78 municípios

# Agrupando os dados por região

In [71]:
grupos_regiao = dataframe.groupby('regiao')
grupos_regiao

In [72]:
print(len(grupos_regiao))

5

In [73]:
for regiao, dataframe_regiao in grupos_regiao:
    media_nota_redacao = dataframe_regiao['nota_redacao'].mean() # Cálculo da média
    desvio_padrao_nota_redacao = dataframe_regiao['nota_redacao'].std() # Cálculo do desvio padrão
    menor_nota = dataframe_regiao['nota_redacao'].min()
    maior_nota = dataframe_regiao['nota_redacao'].max()
    amplitude = maior_nota - menor_nota

    #print(f'\nRegião: {regiao} {len(dataframe_regiao)}')
    print(regiao)
    print(f'{"Quantidade de dados":<30}{len(dataframe_regiao):>7d}')
    print(f'{"Média Nota Redação":<30} {media_nota_redacao:>6.2f}')
    print(f'{"Desvio Padrão Nota Redação":<30} {desvio_padrao_nota_redacao:>6.2f}')
    print(f'{"Menor Nota Redação":<30} {menor_nota:>6.2f}')
    print(f'{"Maior Nota Redação":<30} {maior_nota:>6.2f}')
    print(f"{'Amplitude':<30} {amplitude:>6.2f}\n")

CENTRO-OESTE
Quantidade de dados               467
Média Nota Redação             486.55
Desvio Padrão Nota Redação      39.91
Menor Nota Redação             337.78
Maior Nota Redação             594.23
Amplitude                      256.46

NORDESTE
Quantidade de dados              1794
Média Nota Redação             485.73
Desvio Padrão Nota Redação      42.47
Menor Nota Redação             320.00
Maior Nota Redação             622.44
Amplitude                      302.44

NORTE
Quantidade de dados               450
Média Nota Redação             470.63
Desvio Padrão Nota Redação      36.70
Menor Nota Redação             330.94
Maior Nota Redação             568.33
Amplitude                      237.40

SUDESTE
Quantidade de dados              1668
Média Nota Redação             517.26
Desvio Padrão Nota Redação      42.09
Menor Nota Redação             356.67
Maior Nota Redação             646.36
Amplitude                      289.70

SUL
Quantidade de dados              1191
Média Nota Redação             522.32
Desvio Padrão Nota Redação      38.76
Menor Nota Redação             372.00
Maior Nota Redação             668.00
Amplitude                      296.00